### ISSUE TITLE
Improper Database Design

### ISSUE THREAD

**Issue by longnd** [myat-hsu-mon/web-scrapping-app#21]
## Issue
There are 3 tables in the database (users, keywords & results), defined through Sequelize models
https://github.com/myat-hsu-mon/web-scrapping-app/tree/main/server/src/models
But none of them have
- relationships defined (e.g. `users` <-> `keywords`)
- no indices for foreign keys (e.g. `userID` in keywords table)
- all foreign keys are nullable
- all primary attributes in all tables are nullable (e.g. "name" & "userID" in keywords table)

The current design can't ensure data integrity. 

Besides that, the current implementation (model definition) doesn't utilize all of the features of Sequelize, e.g. email validation.
https://sequelize.org/docs/v6/core-concepts/validations-and-constraints/#per-attribute-validations
as a result, the use of a 3rd party package for validation is unnecessary
 
https://github.com/myat-hsu-mon/web-scrapping-app/blob/120bc39b82ccb5a1e9c3da8f92aee776fbe7f717/server/src/controllers/authController.js#L4

## Expected
The DB schema has proper design.

**Comment by myat-hsu-mon** [comment]
Thank you for providing such detailed feedback on the database schema. I appreciate your insights. In the initial schema design, I manually created the schema without establishing explicit relations, which I now recognize as a potential weakness. In response to this, I've made significant improvements to the schema design. In the updated version, I've implemented database migrations, introduced associations, and incorporated validations. You can review the changes in the [PR](https://github.com/myat-hsu-mon/web-scrapping-app/pull/27). I believe these enhancements will contribute to a more robust and maintainable system. If you have any further thoughts or suggestions, please feel free to share them.
