### ISSUE TITLE
No test for the core business domain

### ISSUE THREAD

**Issue by longnd** [myat-hsu-mon/web-scrapping-app#22]
## Issue
Besides the test for the front-end app, there are no tests for the backend. While 100% test coverage is not expected, the core business domain (file upload, scrapping service) should be tested.

## Expected
The core business domain is tested

**Comment by myat-hsu-mon** [comment]
Thank you for your valuable suggestions. Specifically, I have implemented a suite of unit tests focusing on the core business domain. These tests cover crucial functionalities such as file upload, scraping services, and retrieving both keywords and keyword details with their respective results. These tests aim to ensure the reliability and correctness of the application's key features. if you have any additional recommendations or areas for improvement, I'm eager to hear them.
