### ISSUE TITLE
[Bug] Broken UI when showing HTML content of the search result

### ISSUE THREAD

**Issue by longnd** [myat-hsu-mon/web-scrapping-app#23]
## Issue
When showing the HTML content of a search result, the UI is broken. The way to embed the HTML content inside the div tag is the culprit. 
![image](https://github.com/myat-hsu-mon/web-scrapping-app/assets/1896814/fa202db5-9271-4e59-aaf5-48556ed88612)
![image](https://github.com/myat-hsu-mon/web-scrapping-app/assets/1896814/6bec0cd1-2078-4b3e-9e8e-2c99eea5e165)

Isn't using a `<iframe>` tag is better?

**Comment by myat-hsu-mon** [comment]
Thank you for your suggestions. I've implemented the use of the <iframe> tag, and I'm pleased to share that it has significantly improved the UI, resolving any issues with breakage. In this particular instance, I've opted for a fixed height within the iframe to display the Google search results seamlessly. If you have any further recommendations, I would be happy to hear.
