### ISSUE TITLE
[Bug] The website forces the user to log in again every time the page is refreshed

### ISSUE THREAD

**Issue by longnd** [myat-hsu-mon/web-scrapping-app#25]
## Issue
Every time the user refreshes a page, the session is gone, and the application forces logging in again.

https://github.com/myat-hsu-mon/web-scrapping-app/assets/1896814/5229980e-215e-470e-9c25-dc7aae1d60d5

**Comment by myat-hsu-mon** [comment]
Thank you for your valuable advice. I've implemented updates to enhance user experience by saving login credentials. As a result, users will no longer encounter the need to log in every time the page is refreshed.
